apiVersion: skaffold/v2beta29
kind: Config
metadata: 
  name: CockroachDB
profiles:
  - name: development-cockroachdb
    deploy:
      helm: 
        releases:
          - name: cockroachdb
            remoteChart: cockroachdb
            repo: https://charts.cockroachdb.com
            version: 8.1.4
            setValues:
              conf:
                cache: "2Gi"
                max-sql-memory: "2Gi"
