# Ref: https://docs.yugabyte.com/preview/deploy/kubernetes/single-zone/oss/helm-chart/#on-minikube
apiVersion: skaffold/v3
kind: Config
metadata:
  name: Yugabyte
profiles:
  - name: development-yugabyte
    activation:
      - kubeContext: minikube
    deploy:
      helm:
        releases:
          - name: yugabyte
            repo: https://charts.yugabyte.com
            remoteChart: yugabyte
            version: 2.17.0
            namespace: yb-demo
            createNamespace: true
            setValues:
              resource:
                master:
                  requests:
                    cpu: 0.5
                    memory: 0.5Gi
                tserver:
                  requests:
                    cpu: 0.5
                    memory: 0.5Gi
              enableLoadBalancer: false
