apiVersion: skaffold/v3
kind: Config
metadata:
  name: Infrastructure
requires:
  - path: yugabytedb 
    activeProfiles:
      - name: development-yugabyte
        activatedBy:
          - development-infra
  - path: mongodb
    activeProfiles:
      - name: development-mongodb
        activatedBy:
          - development-infra
profiles:
  - name: development-infra
    activation:
      - kubeContext: minikube